### ISSUE TITLE
AdaptNLP v0.2.x Additional Features Discussion

### ISSUE THREAD

**Issue by aychang95** [Novetta/adaptnlp#10]
There are a lot of ideas that may be floating for feature implementations, so this thread just provides a mini roadmap and environment to think about adaptnlp's progression.

Ideas can be stated freely in this thread and do not replace feature-request issue posts.

- [x] **Tokenizer** Start integrating tokenizers all across adaptnlp for speed and performance enhancements for training and inference.
- [x] **Summarization** Add NLP-task of summarization using document-level encoder based on transformer language models
- [x] **GPU** Multi-GPU and mixed-precision is prevalent in AdaptNLP, but its implementation can be improved and debugged
~~**FastAPI Batch-Serving** Improve on the concurrent calls with batch processing from the NLP models (maybe try to make it CPU and GPU agnostic for ease-of-use)~~
~~**Model Downloading** Start structuring a way to download and potentially upload pre-trained NLP-task models~~

**Comment by haunkbn99** [comment]
sorry! can you write all of "tag_type" - example: "ner"

**Comment by aychang95** [comment]
@haunkbn99 

You're talking about the `tag_type` params for the built-in methods for `Sentence` objects like `get_spans()` and `to_dict()` right?  I should have specified this a little more in the documention!

Here are some for the pre-trained models Flair provides:

| tag_type | Description |
| -------------    | ------------- |
| 'ner' | For Named Entity Recognition tagged text |
| 'pos' | For Parts of Speech tagged text |
| 'np' | For Syntactic Chunking tagged text |

I've also added this to the documentation [here](https://novetta.github.io/adaptnlp/tutorial/token-tagging.html).  Please let me know if you're looking for something else!

Also, if you'd like you can open issues labeled as "question" for this and other questions in the future so that I can better triage any issues/questions that you have!

**Comment by haunkbn99** [comment]
@aychang95 Thank you so much! I found it.
