### ISSUE TITLE
AttributeError: 'CamembertForMaskedLM' object has no attribute 'cls'

### ISSUE THREAD

**Issue by NicoLivesey** [Novetta/adaptnlp#36]
**Describe the bug**
Trying to freeze a LMFinetuner based on Camembert weights and get:

> ---------------------------------------------------------------------------
> AttributeError                            Traceback (most recent call last)
> <ipython-input-13-2a5c01caf20b> in <module>
>       6              }
>       7 finetuner = LMFineTuner(**ft_configs)
> ----> 8 finetuner.freeze()
> 
> ~/anaconda3/envs/pe_adaptnlp/lib/python3.8/site-packages/adaptnlp/transformers/finetuning.py in freeze(self)
>    1630         """Freeze last classification layer group only
>    1631         """
> -> 1632         layers_len = len(list(self.model.cls.parameters()))
>    1633         self.freeze_to(-layers_len)
>    1634 
> 
> ~/anaconda3/envs/pe_adaptnlp/lib/python3.8/site-packages/torch/nn/modules/module.py in __getattr__(self, name)
>     573             if name in modules:
>     574                 return modules[name]
> --> 575         raise AttributeError("'{}' object has no attribute '{}'".format(
>     576             type(self).__name__, name))
>     577 
> 
> AttributeError: 'CamembertForMaskedLM' object has no attribute 'cls'

**To Reproduce**
```
from adaptnlp import LMFineTuner
train_file = "path/to/train" 
valid_file = "path/to/valid"
ft_configs = {
              "train_data_file": train_file,
              "eval_data_file": valid_file,
              "model_type": "camembert",
              "model_name_or_path": "camembert-base",
             }
finetuner = LMFineTuner(**ft_configs)
finetuner.freeze()
```

**Expected behavior**
No error

**Desktop (please complete the following information):**
 - OS: Amazon Linux
 - Browser Chrome

**Comment by NicoLivesey** [comment]
The Language Model Head in CamemBERT is called "lm_head" and not "cls"
Issue fixed with `finetuner.freeze_to(-len(list(model.lm_head.parameters()))`

**Comment by aychang95** [comment]
Oh nice, that's the perfect current solution since we have not "normalized" the names of the layer groups yet!

Thank you for bringing this issue up, we should be addressing this in the next release so hopefully that'll make things more convenient for you and other users.

Feel free to create a **bug** issue for us to reference our PRs concerning this!

**Comment by NicoLivesey** [comment]
You're welcome ! :)

**Comment by UrszulaCzerwinska** [comment]
> 
> 
> The Language Model Head in CamemBERT is called "lm_head" and not "cls"
> Issue fixed with `finetuner.freeze_to(-len(list(model.lm_head.parameters()))`

Model is not defined? how do you use it precisely to fix the bug?
