### ISSUE TITLE
Can't load big dataset

### ISSUE THREAD

**Issue by NicoLivesey** [Novetta/adaptnlp#41]
**Describe the bug**
It happens when I want to 
`learning_rate = finetuner.find_learning_rate(**learning_rate_finder_configs)` 
in the tutorial. I have a big dataset with 200k rows and each of them has a text with around 200 words.

In your code when you instantiate the TextDataset, the line 
[`tokenized_text = tokenizer.convert_tokens_to_ids(tokenizer.tokenize(text))`](https://github.com/Novetta/adaptnlp/blob/0c75fced77e769241cc9ee4f19e4ad06f96eef90/adaptnlp/transformers/finetuning.py#L123) 
takes an eternity for a text of 20 million words. Do you think it can be achieved in the better/faster way like by keeping the rows like they are ?

For the record:
Time for 100 characters: 0.0003399848937988281s
Time for 1000 characters: 0.00124359130859375s
Time for 10 000 characters: 0.012135982513427734s
Time for 100 000 characters: 0.2131056785583496s
Time for 1 000 000 characters: 8.782422542572021s
Time for 10 000 000 characters: 734.5397665500641s

Can't reach the end of the full TextDataset (109 610 928 characters). 

**To Reproduce**
Tutorial with a big dataset

**Comment by aychang95** [comment]
Thanks for bringing this up and really appreciate the char/time data.  Hmm it's interesting that the time still increases exponentially, even taking into account the 10x character jumps.  I'll do a deeper dive into this, we've been looking into the alternative [**tokenizers**](https://github.com/huggingface/tokenizers) library which is built on top of rust with one of its main factors being a massive speed up in tokenization.

For any immediate things you could do for this issue, if your train/eval data is pretty well distributed you could change the data path your working with via. `finetuner.train_data_file = "path/to/train/data"` and start splitting your data so you can atleast start training without having to register all 100mil char into the TextDataset.  It's not very ideal so I'll work on addressing this issue now!

Thanks again, and please let me know if you have any other issues or questions that may come up :)
We'll keep this issue open as we address it

**Comment by NicoLivesey** [comment]
Thank you for the temporary solution and your reactivity. 
I will give another try maybe tomorrow by splitting my dataset in several subparts and finetuning each of them one by one. I will keep you updated.

It's my pleasure, AdaptNLP is a really nice project !

**Comment by aychang95** [comment]
@NicoLivesey It's been a while but AdaptNLP's new fine-tuning framework uses a lot of huggingface's implementations that integrate tokenizers and datasets. This should have made the fine-tuning process more clear and MUCH faster in terms of data processing and loading. Hoping this is helpful if at all still relevant!

**Comment by NicoLivesey** [comment]
Hi @aychang95 I moved on to other projects but thanks for letting me know. It's really great to see project like yours moving fast !

**Comment by aychang95** [comment]
Thanks @NicoLivesey! Good luck on your projects and again, really appreciate your inputs/issue on this
