### ISSUE TITLE
Transformers 2.5.0 Update

### ISSUE THREAD

**Issue by aychang95** [Novetta/adaptnlp#5]
Leverage [tokenizer](https://github.com/huggingface/tokenizers) library for transformers and adaptnlp
  - Compare fast tokenizers with flair defaults and wherever tokenizers are used for adaptnlp

Address any incompatibility issues in this issues thread.

**Comment by swayson** [comment]
Seems they integrated the `tokenizers` into `transformers` now. Also v.2.6 is out
