### ISSUE TITLE
EasyDocumentEmbeddings and pre-trained models in local dir

### ISSUE THREAD

**Issue by mattivi** [Novetta/adaptnlp#58]
**Describe the bug**
EasyDocumentEmbeddings does not load a fine-tuned model saved in local dir.

**To Reproduce**
1. Go to https://novetta.github.io/adaptnlp/tutorial/fine-tuning-language-model.html 
2. Follow all steps in the above documentation page:
2.1 Load a pre-trained "bert-base-cased" model
```python
ft_configs = {
              "train_data_file": train_data_file,
              "eval_data_file": eval_data_file,
              "model_type": "bert",
              "model_name_or_path": "bert-base-cased",
              "mlm": True,
              "mlm_probability": 0.15,
              "config_name": None,
              "tokenizer_name": None,
              "cache_dir": None,
              "block_size": -1,
              "no_cuda": False,
              "overwrite_cache": False,
              "seed": 42,
              "fp16": False,
              "fp16_opt_level": "O1",
              "local_rank": -1,
             }
finetuner = LMFineTuner(**ft_configs)
finetuner.freeze()
```
2.2 Find suitable learning rate 
```python
learning_rate_finder_configs = {
    "base_path": OUTPUT_DIR,
    "file_name": "learning_rate.tsv",
    "start_learning_rate": 1e-7,
    "end_learning_rate": 10,
    "iterations": 100,
    "mini_batch_size": 8,
    "stop_early": True,
    "smoothing_factor": 0.7,
    "adam_epsilon": 1e-8,
    "weight_decay": 0.0,
}
learning_rate = finetuner.find_learning_rate(**learning_rate_finder_configs)
finetuner.freeze()
```
2.3 Fine tune it with One cycle policy. OUTPUT_DIR is where model is saved
```python
train_configs = {
    "output_dir": OUTPUT_DIR,
    "should_continue": False,
    "overwrite_output_dir": True,
    "evaluate_during_training": True,
    "per_gpu_train_batch_size": 4,
    "gradient_accumulation_steps": 1,
    "learning_rate": learning_rate,
    "weight_decay": 0.0,
    "adam_epsilon": 1e-8,
    "max_grad_norm": 1.0,
    "num_train_epochs": 10.0,
    "max_steps": -1,
    "warmup_steps": 0,
    "logging_steps": 50,
    "save_steps": 50,
    "save_total_limit": None,
    "use_tensorboard": False,
}
finetuner.train_one_cycle(**train_configs)
```
2.4
Instantiate a downstream task as 
```python
from adaptnlp import EasyDocumentEmbeddings
doc_embeddings = EasyDocumentEmbeddings(OUTPUT_DIR) 
```

3. I get the following error
```
May need a couple moments to instantiate...
Corresponding flair embedding module not found for ...my_directory\finetunedmodel\
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-38-3f24c4b91aac> in <module>
      1 from adaptnlp import EasyDocumentEmbeddings
      2 
----> 3 doc_embeddings = EasyDocumentEmbeddings(OUTPUT_DIR)

~\.conda\envs\adaptnlp\lib\site-packages\adaptnlp\embeddings.py in __init__(self, methods, configs, *embeddings)
    353                 )
    354 
--> 355         assert len(self.embedding_stack) != 0
    356         if "pool" in methods:
    357             self.pool_embeddings = DocumentPoolEmbeddings(

AssertionError: 
```

**Expected behavior**
Expected is to have EasyDocumentEmbeddings instantiated with the finetuned model, the one saved in OUTPUT_DIR.  Am I missing any step?

**Desktop (please complete the following information):**
 - OS: Window 10
 - Packages
-- python 3.6.10
-- adaptnlp '0.1.4'

**Comment by aychang95** [comment]
Hi @mattivi, try renaming your `OUTPUT_DIR` value where your fine-tuned model is saved so that it has "bert" in the name, i.e. `OUTPUT_DIR = "fine-tuned-bert-base-cased-v1"`.  If that works, you should be able to embed documents with: `doc_embeddings.embed_pool(text="Sequence of texts you'd like to embed")`.  This will return a list of Flair `Sentence` objects with which you can access the embeddings through the `embedding` property: `Sentence.embedding`.

Sorry if I don't make this clear in the documentation or if it's a pain, but that's how the `EasyDocumentEmbeddings` automatically extracts the "correct" embedding layers.  I'll try to make this more clear and maybe even switch to a design that doesn't rely on user input for model loading.

I hope this helps, and please let me know or post another issue if you run into any other issues!

**Comment by mattivi** [comment]
Thanks a lot for very quick reply, now it works!
