### ISSUE TITLE
BrokenPipeError when using cells

### ISSUE THREAD

**Issue by iplaughlin** [Novetta/adaptnlp#68]
**Describe the bug**
When running code in cells (as below), receive a BrokenPipeError. Code runs fine in line by line.  

**To Reproduce**
Run the following in cell format in Spyder 4.1.2 running Python 3.7
from adaptnlp import EasyQuestionAnswering 

#%%
## Example Query and Context 
query = "What is the meaning of life?"
context = "Machine Learning is the meaning of life."
top_n = 5

#%%
## Load the QA module and run inference on results 
qa = EasyQuestionAnswering()
best_answer, best_n_answers = qa.predict_qa(query=query, context=context, n_best_size=top_n, mini_batch_size=1, model_name_or_path="distilbert-base-uncased-distilled-squad")

#%%
## Output top answer as well as top 5 answers
print(best_answer)
print(best_n_answers)

**Expected behavior**
Print best_answer and best_n_answers.

**Desktop (please complete the following information):**
 - OS: Win10 on VM
 - Version: Spyder 4.1.2 w/ Python 3.7

**Additional context**
Only occurs in Spyder, not in Jupyter Notebooks.

**Comment by aychang95** [comment]
I have not used spyder much but I will try to replicate this.  Since it works in jupyter and via. interpreter that's a good sign.

Thanks for bringing this up!

**Comment by aychang95** [comment]
Will consolidate with near future ipython/notebook updates and win10 support.
