### ISSUE TITLE
ImportError: cannot import name 'EasyTokenTagger'

### ISSUE THREAD

**Issue by RAbraham** [Novetta/adaptnlp#74]
**Describe the bug**
I tried to run the code in the tutorial 
```
from adaptnlp import EasyTokenTagger


## Example Text
example_text = "Novetta's headquarters is located in Mclean, Virginia."

## Load the token tagger module and tag text with the NER model 
tagger = EasyTokenTagger()
sentences = tagger.tag_text(text=example_text, model_name_or_path="ner")

## Output tagged token span results in Flair's Sentence object model
for sentence in sentences:
    for entity in sentence.get_spans("ner"):
        print(entity)
```
and it gave me the error:

```
...
  File "/home/rajiv/Documents/dev/python/nltk-trial/adaptnlp.py", line 2, in <module>
    from adaptnlp import EasyTokenTagger
ImportError: cannot import name 'EasyTokenTagger'
```

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version: 20.04
 - Python:  3.6.9

**Comment by aychang95** [comment]
It may be because the file name is `adaptnlp.py`, I usually try to stay clear from duplicate naming of packages and local modules since the package imports can get pretty mixed up.

If that isn't the issue, could you make sure the package is installed via. `pip freeze`

**Comment by RAbraham** [comment]
lol. That is correct. Thanks!
